language: node_js
node_js:
  - 14
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - npm ci
deploy:
  on:
    main
    # all_branches: true
  provider: heroku
  app: mindfulnessmood
  api_key:
    secure: edWZSRO1+AlQQkNlQCxCbWUuNLeuKvkIN/PyFfKTe4q7oUZISWNGBn/2+s3yKAosoHq9pS8mIeMH/MgHq1vrH0hwlnq/OW6vMDpjxHD3MqnGG9lio/iy1gBnBvvnYNq2IVx2+gElPPG2SEmkgVZt4bp+uIF9kkHKtSh0IoPNi/p8+wOAnzrqCWjNlLCIPAVwXoLDvUovna8rlEMYE7tInHkFIBlcLE/8dPOODp/AgGAYYvELU3hFMZA5JXdVBZtQduhZxXtyS676uD9mA6xdZ3Su+WEWMgfSikIN9RoXXPkexwacEkf06QAhG1kXYK+HuRrL1Z3L5EGj9egxB7xsuVPle+3JFEM5LnxvXXGpmGV/J1oPY3gV5bMHqUAoXIQjjzQxx7HSRTLPIC+b+eeg/IpAStSwHmNAR74o5pW6ff2ivt/M9DibIW2DltDXGqmdMMxUUhZl4RYivd1c/QPET4ySCRQlOhulIGt7jmGeasvxn+eCaI2tGIghYdwewDDPaSbyw5L+lh4pkB7ZA42H4xsLqszlOKpRwvg/9v6NxX91V9WwaZ/xLcP9+tGoUqUPhla6bq2j1juGmRfWHK18R9h6VhHoI81Jf4ER3vTPX1bv9NYBVpmOfz5siHtW32r+RavpkK/3r5QaKNyJP66lYQZXKP0DVki32ue9K1RZAug=
